apiVersion: apps/v1
kind: Deployment
metadata:
  name: exec-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      service: exec
  template:
    metadata:
      labels:
        type: app
        service: exec
    spec:
      containers:
        - name: exec
          image: cooperatoolcr.azurecr.io/exec
          env:
            - name: eurekaSvc
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: eurekaSvc
            - name: eurekaPort
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: eurekaPort
            - name: MySQL_URL
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MySQL_URL
            - name: MySQL_PORT
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MySQL_PORT
            - name: MySQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MySQL_USER
            - name: MySQL_PW
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MySQL_PW
            - name: MySQL_DB
              valueFrom:
                secretKeyRef:
                  name: mysql-info
                  key: MySQL_DB
---
apiVersion: v1
kind: Service
metadata:
  name: exec-svc
spec:
  ports:
    - port: 8400
      protocol: TCP
      targetPort: 8400
  selector:
    type: app
    service: exec