server:
  port: 8700
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eurekaSvc}:${eurekaPort}/eureka/

