apiVersion: v1
kind: Service
metadata:
  name: database-service
  labels:
    run: database-service
spec:
  ports:
    - port: 88
      protocol: TCP
      targetPort: 8081
  selector:
    app: database-docker #endpoint pod에 연결