apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dp
spec:
  replicas: 1
  selector:
    matchLabels:
      type: app
      service: web
  template:
    metadata:
      labels:
        type: app
        service: web
    spec:
      containers:
        - name: web
          image: cooperatoolcr.azurecr.io/web2
          env:
            - name: eurekaSvc
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: eurekaSvc
            - name: eurekaPort
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: eurekaPort
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    type: app
    service: web